DROP TABLE IF EXISTS COFFEE_DESCRIPTIONS;
DROP TABLE IF EXISTS COFFEE_HOUSES;
DROP TABLE IF EXISTS MERCH_INVENTORY;
DROP TABLE IF EXISTS COF_INVENTORY;
DROP TABLE IF EXISTS RSS_FEEDS;
DROP TABLE IF EXISTS COFFEES;
DROP TABLE IF EXISTS SUPPLIERS;
DROP TABLE IF EXISTS DATA_REPOSITORY;
