/* AUTO-GENERATED FILE.	DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.	It
 * should not be modified by hand.
 */

package com.commonsware.android.prefs;

public final class R {
		public static final class array {
				public static final int airport_codes=0x7f050001;
				public static final int cities=0x7f050000;
		}
		public static final class attr {
		}
		public static final class drawable {
				public static final int eject=0x7f020000;
				public static final int misc=0x7f020001;
		}
		public static final class id {
				public static final int checkbox=0x7f070000;
				public static final int checkbox2=0x7f070002;
				public static final int list=0x7f070004;
				public static final int ringtone=0x7f070001;
				public static final int text=0x7f070003;
		}
		public static final class layout {
				public static final int main=0x7f030000;
		}
		public static final class string {
				public static final int app_name=0x7f060000;
				public static final int checkbox=0x7f060001;
				public static final int checkbox2=0x7f060003;
				public static final int list=0x7f060005;
				public static final int ringtone=0x7f060002;
				public static final int text=0x7f060004;
		}
		public static final class xml {
				public static final int preferences=0x7f040000;
		}
}