/* AUTO-GENERATED FILE.	DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.	It
 * should not be modified by hand.
 */

package com.commonsware.android.search;

public final class R {
		public static final class attr {
		}
		public static final class drawable {
				public static final int eject=0x7f020000;
				public static final int search=0x7f020001;
		}
		public static final class id {
				public static final int selection=0x7f060000;
		}
		public static final class layout {
				public static final int main=0x7f030000;
		}
		public static final class string {
				public static final int app_name=0x7f050000;
				public static final int searchHint=0x7f050002;
				public static final int searchLabel=0x7f050001;
		}
		public static final class xml {
				public static final int searchable=0x7f040000;
				public static final int words=0x7f040001;
		}
}