/* AUTO-GENERATED FILE.	DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.	It
 * should not be modified by hand.
 */

package com.commonsware.android.menus;

public final class R {
		public static final class attr {
		}
		public static final class drawable {
				public static final int eject=0x7f020000;
		}
		public static final class id {
				public static final int close=0x7f060000;
				public static final int disabled=0x7f060002;
				public static final int ghost=0x7f060008;
				public static final int last=0x7f060005;
				public static final int later=0x7f060004;
				public static final int no_icon=0x7f060001;
				public static final int non_ghost=0x7f060007;
				public static final int other_stuff=0x7f060003;
				public static final int submenu=0x7f060006;
		}
		public static final class layout {
				public static final int main=0x7f030000;
		}
		public static final class menu {
				public static final int sample=0x7f050000;
		}
		public static final class string {
				public static final int app_name=0x7f040000;
		}
}