/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opengl_jni_Natives */

#ifndef _Included_opengl_jni_Natives
#define _Included_opengl_jni_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opengl_jni_Natives
 * Method:    NativeRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_opengl_jni_Natives_NativeRender
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
