DROP TABLE COFFEE_DESCRIPTIONS;
DROP TABLE COFFEE_HOUSES;
DROP TABLE MERCH_INVENTORY;
DROP TABLE COF_INVENTORY;
DROP TABLE RSS_FEEDS;
DROP TABLE COFFEES;
DROP TABLE SUPPLIERS;
DROP TABLE DATA_REPOSITORY;