/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wolf_jni_Natives */

#ifndef _Included_wolf_jni_Natives
#define _Included_wolf_jni_Natives
#ifdef __cplusplus
extern "C" {
#endif
#undef wolf_jni_Natives_EV_KEYDOWN
#define wolf_jni_Natives_EV_KEYDOWN 0L
#undef wolf_jni_Natives_EV_KEYUP
#define wolf_jni_Natives_EV_KEYUP 1L
#undef wolf_jni_Natives_EV_MOUSE
#define wolf_jni_Natives_EV_MOUSE 2L
/*
 * Class:     wolf_jni_Natives
 * Method:    WolfMain
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wolf_jni_Natives_WolfMain
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     wolf_jni_Natives
 * Method:    keyPress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_wolf_jni_Natives_keyPress
  (JNIEnv *, jclass, jint);

/*
 * Class:     wolf_jni_Natives
 * Method:    keyRelease
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_wolf_jni_Natives_keyRelease
  (JNIEnv *, jclass, jint);

/*
 * Class:     wolf_jni_Natives
 * Method:    motionEvent
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_wolf_jni_Natives_motionEvent
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
