/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wolf_jni_Natives_EventListener */

#ifndef _Included_wolf_jni_Natives_EventListener
#define _Included_wolf_jni_Natives_EventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
