/* AUTO-GENERATED FILE.	DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.	It
 * should not be modified by hand.
 */

package com.commonsware.android.containers;

public final class R {
		public static final class attr {
		}
		public static final class id {
				public static final int center=0x7f040005;
				public static final int gravity=0x7f040003;
				public static final int horizontal=0x7f040001;
				public static final int left=0x7f040004;
				public static final int orientation=0x7f040000;
				public static final int right=0x7f040006;
				public static final int vertical=0x7f040002;
		}
		public static final class layout {
				public static final int main=0x7f020000;
		}
		public static final class string {
				public static final int app_name=0x7f030000;
		}
}